---
- name: Converge
  hosts: all

  vars:
    apache2_default_http_port: >-
      {{ 8080 + play_hosts.index(inventory_hostname) }}

    apache2_default_https_port: >-
      {{ 4340 + play_hosts.index(inventory_hostname) }}

    apache2_extra_ports:
      - "{{ 1310 + play_hosts.index(inventory_hostname) }}"
      - "{{ 3130 + play_hosts.index(inventory_hostname) }}"

    apache2_create_default: true
    apache2_create_default_ssl: true

    apache2_https_redirect: true

    apache2_certificate_paths:
      Alpine: /etc/ssl/apache2/server.pem
      Debian: /etc/ssl/certs/ssl-cert-snakeoil.pem
      Solaris: /opt/local/etc/ssl/httpd/server.pem

    apache2_certificate_key_paths:
      Alpine: /etc/ssl/apache2/server.key
      Debian: /etc/ssl/private/ssl-cert-snakeoil.key
      Solaris: /opt/local/etc/ssl/httpd/server.key

    apache2_certificate_file: >-
      {{ apache2_certificate_paths[ansible_os_family] }}

    apache2_certificate_key_file: >-
      {{ apache2_certificate_key_paths[ansible_os_family] }}

    apache2_os_packages:
      apk:
        - apache2-mod-wsgi
        - apache2-ssl
        - py2-pip
      apt:
        - libapache2-mod-wsgi
        - libapache2-mod-xsendfile
        - python-setuptools
      pkgin:
        - ap24-xsendfile
        - py37-ap24-mod_wsgi
        - py37-pip

    apache2_packages: >-
      {{ apache2_os_packages[ansible_pkg_mgr] | default([]) }}

    apache2_modules:
      - wsgi
      - xsendfile

  vars_files:
    - goss.yml

  roles:
    - role: apache2

  tasks:
    - name: Create default index page
      copy:
        content: 'Ansible Configured Apache2 server package'
        dest: "{{ apache2_base_path }}/index.html"
        mode: 0644
        owner: "{{ apache2_user }}"
        group: "{{ apache2_group }}"

    - name: Install required python packages
      pip:
        name: xsendfile
        executable: "/usr/bin/pip{% if ansible_os_family == 'Alpine' and ansible_facts['distribution_version'] is version('3.11', '>=') %}3{% endif %}"

    - name: Install helper script
      template:
        src: xsendfile.wsgi
        dest: "{{ apache2_base_path }}"
        mode: 0755
        owner: "{{ apache2_user }}"
        group: "{{ apache2_group }}"

    - name: Configure apache2 to serve the application
      copy:
        dest: "{{ apache2_config_enabled_path }}/test_xsendfile.conf"
        mode: 0644
        content: |
          WSGIScriptAlias /download {{ apache2_base_path }}/xsendfile.wsgi

          <IfModule xsendfile_module>
             XSendFile on
             XSendFilePath "{{ apache2_base_path }}"
          </IfModule>
      notify: restart apache2

    - name: Create help file for testing
      copy:
        dest: "{{ apache2_base_path }}/hello.txt"
        mode: 0644
        owner: "{{ apache2_user }}"
        group: "{{ apache2_group }}"
        content:
          Hello World !!

    - name: Create link to apache WSGI module
      file:
        src: /opt/local/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.so
        dest: /opt/local/lib/httpd/mod_wsgi.so
        state: link
        mode: 0644
        owner: "{{ apache2_user }}"
        group: "{{ apache2_group }}"
      when: ansible_distribution == 'SmartOS'
      notify: restart apache2

    - name: Dump host variables for role
      template: src=config.yml.j2 dest={{ goss_test_variables }} mode=0644
