---
- name: Prepare
  hosts: all

  tasks:
    - name: Setup local package cache
      file:
        src: /var/cache/apk
        dest: /etc/apk/cache
        state: link
      when: ansible_os_family == 'Alpine'

    - name: Setup image for keeping downloaded packages
      file:
        path: /etc/apt/apt.conf.d/docker-clean
        state: absent
      when: ansible_os_family == 'Debian'

    - name: Create certificate for testing
      when: ansible_distribution == 'SmartOS'
      block:
        - name: Create certificate folder
          file:
            path: /opt/local/etc/ssl/httpd
            state: directory

        - name: Generate the certificate
          command: >
            openssl req -newkey rsa:2048 -nodes -x509 -days 365
               -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"
               -keyout /opt/local/etc/ssl/httpd/server.key
               -out /opt/local/etc/ssl/httpd/server.pem
          args:
            creates: /opt/local/etc/ssl/httpd/server.pem
