---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: apache2-ubuntu-18.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/18.04:/var/cache/apt/archives"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
    enabled: false
